/*
This file is generated by Jopi.js. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/
import {routeBindPage, routeBindVerb} from "jopijs/generated";
import c_r1 from "../mod_errorPages/@routes/error401/page.tsx";
import c_r2 from "../mod_errorPages/@routes/error404/page.tsx";
import c_r3 from "../mod_errorPages/@routes/error500/page.tsx";
import c_r4 from "../mod_learning/@routes/benchmark/reactPage/page.tsx";
import f_r5 from "../mod_learning/@routes/benchmark/getCall/onGET.ts";
import c_r6 from "../mod_learning/@routes/aboutRoles/admin/page.tsx";
import c_r7 from "../mod_learning/@routes/aboutRoles/writer/page.tsx";
import f_r8 from "../mod_learning/@routes/aboutRoles/writer/onPOST.ts";
import c_r9 from "../mod_learning/@routes/aboutRoles/hideIfMissingRole/page.tsx";
import c_r10 from "../mod_learning/@routes/aboutReact/aboutCss/page.tsx";
import c_r11 from "../mod_learning/@routes/aboutReact/aboutUiComponents/page.tsx";
import c_r12 from "../mod_learning/@routes/aboutReact/aboutImages/page.tsx";
import c_r13 from "../mod_learning/@routes/aboutReact/aboutDevMode/page.tsx";
import c_r14 from "../mod_learning/@routes/aboutReact/aboutReactHMR/page.tsx";
import c_r15 from "../mod_learning/@routes/aboutReact/aboutUiComposites/page.tsx";
import c_r16 from "../mod_learning/@routes/aboutRoutes/product/[productId]/page.tsx";
import c_r17 from "../mod_learning/@routes/aboutRoutes/catchAll/hello/page.tsx";
import f_r18 from "../mod_learning/@routes/aboutRoutes/catchAll/[...]/onGET.ts";
import c_r19 from "../mod_learning/@routes/aboutRoutes/page.tsx";
import c_r20 from "../mod_learning/@routes/aboutRoutes/reactPage/page.tsx";
import f_r21 from "../mod_learning/@routes/aboutRoutes/myAPI/onGET.ts";
import f_r22 from "../mod_learning/@routes/aboutRoutes/myAPI/onPOST.ts";
import c_r23 from "../mod_learning/@routes/page.tsx";
import c_r24 from "../mod_learning/@routes/aboutEvents/page.tsx";
import c_r25 from "../mod_userAuth/@routes/login/page.tsx";
import f_r26 from "../mod_userAuth/@routes/login/onPOST.ts";
import {RouteConfig} from "jopijs";
import routeConfig1 from "../mod_learning/@routes/aboutRoles/admin/config.ts";
import routeConfig2 from "../mod_learning/@routes/aboutRoles/writer/config.ts";
import routeConfig3 from "../mod_learning/@routes/aboutRoles/hideIfMissingRole/config.ts";
import routeConfig4 from "../mod_learning/@routes/aboutReact/aboutReactHMR/config.ts";
import routeConfig5 from "../mod_learning/@routes/aboutRoutes/config.ts";
import routeConfig6 from "../mod_userAuth/@routes/login/config.ts";

export default async function(webSite) {
    await routeBindPage(webSite, c_r1, {"route":"/error401","attributes":{},"filePath":"src/mod_errorPages/@routes/error401/page.tsx"});
    await routeBindPage(webSite, c_r2, {"route":"/error404","attributes":{},"filePath":"src/mod_errorPages/@routes/error404/page.tsx"});
    await routeBindPage(webSite, c_r3, {"route":"/error500","attributes":{},"filePath":"src/mod_errorPages/@routes/error500/page.tsx"});
    await routeBindPage(webSite, c_r4, {"route":"/benchmark/reactPage","attributes":{},"filePath":"src/mod_learning/@routes/benchmark/reactPage/page.tsx"});
    await routeBindVerb(webSite, f_r5, {"verb":"GET","route":"/benchmark/getCall","attributes":{},"filePath":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/benchmark/getCall/onGET.ts"});
    await routeBindPage(webSite, c_r6, {"route":"/aboutRoles/admin","attributes":{"needRoles":{"PAGE":["admin"]},"configFile":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutRoles/admin/config.ts"},"filePath":"src/mod_learning/@routes/aboutRoles/admin/page.tsx"});
    await routeBindPage(webSite, c_r7, {"route":"/aboutRoles/writer","attributes":{"needRoles":{"PAGE":["writer"]},"configFile":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutRoles/writer/config.ts"},"filePath":"src/mod_learning/@routes/aboutRoles/writer/page.tsx"});
    await routeBindVerb(webSite, f_r8, {"verb":"POST","route":"/aboutRoles/writer","attributes":{"needRoles":{"PAGE":["writer"]},"configFile":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutRoles/writer/config.ts"},"filePath":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutRoles/writer/onPOST.ts"});
    await routeBindPage(webSite, c_r9, {"route":"/aboutRoles/hideIfMissingRole","attributes":{"configFile":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutRoles/hideIfMissingRole/config.ts"},"filePath":"src/mod_learning/@routes/aboutRoles/hideIfMissingRole/page.tsx"});
    await routeBindPage(webSite, c_r10, {"route":"/aboutReact/aboutCss","attributes":{},"filePath":"src/mod_learning/@routes/aboutReact/aboutCss/page.tsx"});
    await routeBindPage(webSite, c_r11, {"route":"/aboutReact/aboutUiComponents","attributes":{},"filePath":"src/mod_learning/@routes/aboutReact/aboutUiComponents/page.tsx"});
    await routeBindPage(webSite, c_r12, {"route":"/aboutReact/aboutImages","attributes":{},"filePath":"src/mod_learning/@routes/aboutReact/aboutImages/page.tsx"});
    await routeBindPage(webSite, c_r13, {"route":"/aboutReact/aboutDevMode","attributes":{},"filePath":"src/mod_learning/@routes/aboutReact/aboutDevMode/page.tsx"});
    await routeBindPage(webSite, c_r14, {"route":"/aboutReact/aboutReactHMR","attributes":{"configFile":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutReact/aboutReactHMR/config.ts"},"filePath":"src/mod_learning/@routes/aboutReact/aboutReactHMR/page.tsx"});
    await routeBindPage(webSite, c_r15, {"route":"/aboutReact/aboutUiComposites","attributes":{},"filePath":"src/mod_learning/@routes/aboutReact/aboutUiComposites/page.tsx"});
    await routeBindPage(webSite, c_r16, {"route":"/aboutRoutes/product/:productId","attributes":{},"filePath":"src/mod_learning/@routes/aboutRoutes/product/[productId]/page.tsx"});
    await routeBindPage(webSite, c_r17, {"route":"/aboutRoutes/catchAll/hello","attributes":{},"filePath":"src/mod_learning/@routes/aboutRoutes/catchAll/hello/page.tsx"});
    await routeBindVerb(webSite, f_r18, {"verb":"GET","route":"/aboutRoutes/catchAll/**","attributes":{},"filePath":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutRoutes/catchAll/[...]/onGET.ts"});
    await routeBindPage(webSite, c_r19, {"route":"/aboutRoutes","attributes":{"configFile":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutRoutes/config.ts"},"filePath":"src/mod_learning/@routes/aboutRoutes/page.tsx"});
    await routeBindPage(webSite, c_r20, {"route":"/aboutRoutes/reactPage","attributes":{},"filePath":"src/mod_learning/@routes/aboutRoutes/reactPage/page.tsx"});
    await routeBindVerb(webSite, f_r21, {"verb":"GET","route":"/aboutRoutes/myAPI","attributes":{},"filePath":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutRoutes/myAPI/onGET.ts"});
    await routeBindVerb(webSite, f_r22, {"verb":"POST","route":"/aboutRoutes/myAPI","attributes":{},"filePath":"/Users/johan/Projects/jopiDemoProject/src/mod_learning/@routes/aboutRoutes/myAPI/onPOST.ts"});
    await routeBindPage(webSite, c_r23, {"route":"/","attributes":{},"filePath":"src/mod_learning/@routes/page.tsx"});
    await routeBindPage(webSite, c_r24, {"route":"/aboutEvents","attributes":{},"filePath":"src/mod_learning/@routes/aboutEvents/page.tsx"});
    await routeBindPage(webSite, c_r25, {"route":"/login","attributes":{"configFile":"/Users/johan/Projects/jopiDemoProject/src/mod_userAuth/@routes/login/config.ts"},"filePath":"src/mod_userAuth/@routes/login/page.tsx"});
    await routeBindVerb(webSite, f_r26, {"verb":"POST","route":"/login","attributes":{"configFile":"/Users/johan/Projects/jopiDemoProject/src/mod_userAuth/@routes/login/config.ts"},"filePath":"/Users/johan/Projects/jopiDemoProject/src/mod_userAuth/@routes/login/onPOST.ts"});
    await routeConfig1(new RouteConfig(webSite, "/aboutRoles/admin", ["admin"]));
    await routeConfig2(new RouteConfig(webSite, "/aboutRoles/writer", ["writer"]));
    await routeConfig3(new RouteConfig(webSite, "/aboutRoles/hideIfMissingRole"));
    await routeConfig4(new RouteConfig(webSite, "/aboutReact/aboutReactHMR"));
    await routeConfig5(new RouteConfig(webSite, "/aboutRoutes"));
    await routeConfig6(new RouteConfig(webSite, "/login"));
}