/*
This file is generated by Jopi.js. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/
import C from "../../mod_overriding/@alias/uiComponents/mySharedComponent/index.tsx";
export default C;