/*
This file is generated by Jopi.js. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/
import {createStaticEvent} from "jopi-toolkit/jk_events"
import {useStaticEvent} from "jopijs/ui";        
import I1 from "../../mod_overriding/@alias/events/card.product.added/extraListener/index.ts";
import I2 from "../../mod_learning/@alias/events/card.product.added/refreshPrice/index.ts";
import I3 from "../../mod_learning/@alias/events/card.product.added/startAnimation/index.ts";

export const list = [I1,I2,I3,];
const event = createStaticEvent("card.product.added", list);
export default useStaticEvent(event);